package com.g90.backend.modules.contract.entity;

public enum ContractTrackingEventType {
    DRAFT_CREATED,
    UPDATED,
    CUSTOMER_APPROVAL_REQUESTED,
    CUSTOMER_APPROVED,
    CUSTOMER_REJECTED,
    ACCOUNTANT_REJECTED,
    APPROVAL_REQUESTED,
    APPROVED,
    REJECTED,
    SUBMITTED,
    PROCESSING_STARTED,
    INVENTORY_RESERVED,
    RESERVED,
    CANCEL_REQUESTED,
    CANCELLED,
    PICKED,
    SHIPPED,
    DELIVERED,
    COMPLETED,
    DOCUMENT_GENERATED,
    DOCUMENT_EXPORTED,
    DOCUMENT_EMAILED
}
