spring.application.name=g90-backend

spring.datasource.url=jdbc:mysql://localhost:3306/g90_steel
spring.datasource.username=root
spring.datasource.password=root

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.persistAuthorization=true
