ALTER TABLE promotions
ADD COLUMN code VARCHAR(50) NULL;

ALTER TABLE quotations
ADD COLUMN promotion_code VARCHAR(50) NULL,
ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN submitted_at TIMESTAMP NULL;

CREATE UNIQUE INDEX uk_promotions_code ON promotions(code);
